### ISSUE TITLE
Unable To Log In

### ISSUE THREAD

**Issue by Shaneajm** [SQLMatches/Frontend#1]
**Issue:**
When the API server is up and I go to log in I get a missing API Key error on the page and a 500 error on the API server log
```
{"data":null,"error":"APIKeyRequired"}
```
I don't see a location to put in a Steam API key anywhere in the settings on the API server or the frontend. Is it an ENV variable?

Thanks!

**Comment by WardPearce** [comment]
I'm assuming you're using `0.0.13`, this repo is for `0.1.0`.
https://github.com/SQLMatches/Website/tree/API

`0.1.0` is now ready I believe, aside from some minor changes needed to the plugin.

I'll merge the API branch into the master now.

**Comment by Shaneajm** [comment]
You assumed correctly, I was on `0.0.13`. I didn't see the other branch lol.

Thanks for merging!

**Comment by WardPearce** [comment]
https://github.com/SQLMatches/API
I've merged the API branch into master & renamed the repo API.
Hopefully we can get the new plugin ready today.
