### ISSUE TITLE
Implement footer on the site

### ISSUE THREAD

**Issue by crashzk** [SQLMatches/Frontend#3]
It would be good to insert a footer on the site by placing links to the project's GitHub, links to bug reports / suggestions and etc., inserting developer information and tals, just for aesthetic purposes.
![image](https://user-images.githubusercontent.com/32937653/105552692-0bc93780-5ce3-11eb-91a2-4989ed00fc1b.png)

**Comment by WardPearce** [comment]
https://github.com/SQLMatches/Frontend/commit/465c2157f2a6f07aad03a6eaa20cff548b72c905
